version: '3.3'
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recordings_api
    ports:
      - 9090:9090
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env
  mysql:
    image: mysql:5.7
    container_name: recordings_api_mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'recordings'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./scripts/db/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/db/seed.sql:/docker-entrypoint-initdb.d/2.sql"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10